FROM node:18-alpine

WORKDIR /app

# Copy package.json from the backend folder
COPY backend/package*.json ./

RUN npm install

# Copy the rest of the backend code
COPY backend/ .

RUN npm run build

EXPOSE 3000

CMD ["npm", "start"]
